// Auto-generated by KalshiSnipe resolve_calls.py
const DASHBOARD_DATA = {
  "generated_at": "2026-05-29T18:14:11.530717+00:00",
  "total_calls": 1,
  "wins": 0,
  "losses": 0,
  "pending": 1,
  "win_rate": 0,
  "total_pnl": 0,
  "paper_stake_per_call": 100.0,
  "asset_stats": {},
  "recent_calls": [
    {
      "ticker": "KXXRP15M-26MAY291415-15",
      "title": "XRP price up in next 15 mins?",
      "asset": "XRP",
      "called_direction": "YES",
      "mid_price_cents": 60,
      "yes_bid_dollars": "0.5700",
      "yes_ask_dollars": "0.6200",
      "minutes_left": 10.4,
      "consensus": 4,
      "edge_score": 0.4363,
      "close_time": "2026-05-29T18:15:00Z",
      "kalshi_url": "https://kalshi.com/markets/KXXRP15M",
      "posted_at": "2026-05-29T18:05:13.795420+00:00",
      "stake": 100.0,
      "paper_only": true,
      "post_text": "\ud83d\udfe2 <b>XRP Price Up</b>\nWill XRP price be higher in the next 15 minutes?\n<b>\ud83d\udd17 <a href=\"https://kalshi.com/markets/kxxrp15m/KXXRP15M-26MAY291415-15\">View on Kalshi</a></b>\n\nThe Kalshi contract (KXXRP15M-26MAY291415-15) is trading YES at <b>60\u00a2</b>, implying a 60% probability. Momentum is currently UP at <b>0.1813</b>, while the CVD shows positive buying pressure at <b>0.2647</b>. Spot OBI is also UP at <b>0.5976</b>, suggesting bullish sentiment. With <b>10.4 minutes</b> remaining, consider this short-term opportunity.\n\nSignal consensus is currently <b>4/9</b> indicators aligned.\n\n\u26a0\ufe0f Not financial advice. For educational purposes only.",
      "outcome": null,
      "won": null,
      "pnl": null
    }
  ],
  "all_calls": [
    {
      "ticker": "KXXRP15M-26MAY291415-15",
      "title": "XRP price up in next 15 mins?",
      "asset": "XRP",
      "called_direction": "YES",
      "mid_price_cents": 60,
      "yes_bid_dollars": "0.5700",
      "yes_ask_dollars": "0.6200",
      "minutes_left": 10.4,
      "consensus": 4,
      "edge_score": 0.4363,
      "close_time": "2026-05-29T18:15:00Z",
      "kalshi_url": "https://kalshi.com/markets/KXXRP15M",
      "posted_at": "2026-05-29T18:05:13.795420+00:00",
      "stake": 100.0,
      "paper_only": true,
      "post_text": "\ud83d\udfe2 <b>XRP Price Up</b>\nWill XRP price be higher in the next 15 minutes?\n<b>\ud83d\udd17 <a href=\"https://kalshi.com/markets/kxxrp15m/KXXRP15M-26MAY291415-15\">View on Kalshi</a></b>\n\nThe Kalshi contract (KXXRP15M-26MAY291415-15) is trading YES at <b>60\u00a2</b>, implying a 60% probability. Momentum is currently UP at <b>0.1813</b>, while the CVD shows positive buying pressure at <b>0.2647</b>. Spot OBI is also UP at <b>0.5976</b>, suggesting bullish sentiment. With <b>10.4 minutes</b> remaining, consider this short-term opportunity.\n\nSignal consensus is currently <b>4/9</b> indicators aligned.\n\n\u26a0\ufe0f Not financial advice. For educational purposes only.",
      "outcome": null,
      "won": null,
      "pnl": null
    }
  ]
};
