// Auto-generated by KalshiSnipe resolve_calls.py
const DASHBOARD_DATA = {
  "generated_at": "2026-05-31T10:27:47.752239+00:00",
  "total_calls": 1,
  "wins": 1,
  "losses": 0,
  "pending": 0,
  "win_rate": 1.0,
  "total_pnl": 34.0,
  "paper_stake_per_call": 100.0,
  "asset_stats": {
    "BTC": {
      "wins": 1,
      "losses": 0,
      "pnl": 34.0,
      "calls": 1
    }
  },
  "recent_calls": [
    {
      "ticker": "KXBTC15M-26MAY310415-15",
      "title": "BTC price up in next 15 mins?",
      "asset": "BTC",
      "called_direction": "YES",
      "mid_price_cents": 62,
      "yes_bid_dollars": "0.6100",
      "yes_ask_dollars": "0.6200",
      "minutes_left": 14.1,
      "consensus": 4,
      "edge_score": 0.3993,
      "close_time": "2026-05-31T08:15:00Z",
      "kalshi_url": "https://kalshi.com/markets/KXBTC15M",
      "posted_at": "2026-05-31T08:01:31.166257+00:00",
      "stake": 100.0,
      "paper_only": true,
      "post_text": "\ud83d\udfe2 <b>BTC Price Up in 15 Minutes?</b>\n<b>\ud83d\udd17 <a href=\"https://kalshi.com/markets/kxbtc15m/KXBTC15M-26MAY310415-15\">View on Kalshi</a></b>\n\nWill Bitcoin's price be higher in the next 15 minutes? The Kalshi contract (KXBTC15M-26MAY310415-15) is trading YES at <b>62\u00a2</b> (implied 62% probability).\n\nSupporting indicators include: Futures Open Interest (FUTURES_OBI) showing an upward trend at <b>0.7961</b>, positive Cumulative Volume Delta (CVD) at <b>0.3983</b>, and a notable Volume Spike Ratio of <b>2.10x</b>. Spot Open Interest (SPOT_OBI) is also trending upwards at <b>0.886</b>.\n\nTime remaining: <b>14.1 minutes</b>.\n\nSignal consensus: <b>4/9</b> indicators aligned.\n\n\u26a0\ufe0f Not financial advice. For educational purposes only.",
      "outcome": "EXIT",
      "won": true,
      "pnl": 34.0,
      "resolved_at": "2026-05-31T08:06:02.059245+00:00",
      "exit_reason": "TAKE_PROFIT (89% of max)",
      "exit_price": 96
    }
  ],
  "all_calls": [
    {
      "ticker": "KXBTC15M-26MAY310415-15",
      "title": "BTC price up in next 15 mins?",
      "asset": "BTC",
      "called_direction": "YES",
      "mid_price_cents": 62,
      "yes_bid_dollars": "0.6100",
      "yes_ask_dollars": "0.6200",
      "minutes_left": 14.1,
      "consensus": 4,
      "edge_score": 0.3993,
      "close_time": "2026-05-31T08:15:00Z",
      "kalshi_url": "https://kalshi.com/markets/KXBTC15M",
      "posted_at": "2026-05-31T08:01:31.166257+00:00",
      "stake": 100.0,
      "paper_only": true,
      "post_text": "\ud83d\udfe2 <b>BTC Price Up in 15 Minutes?</b>\n<b>\ud83d\udd17 <a href=\"https://kalshi.com/markets/kxbtc15m/KXBTC15M-26MAY310415-15\">View on Kalshi</a></b>\n\nWill Bitcoin's price be higher in the next 15 minutes? The Kalshi contract (KXBTC15M-26MAY310415-15) is trading YES at <b>62\u00a2</b> (implied 62% probability).\n\nSupporting indicators include: Futures Open Interest (FUTURES_OBI) showing an upward trend at <b>0.7961</b>, positive Cumulative Volume Delta (CVD) at <b>0.3983</b>, and a notable Volume Spike Ratio of <b>2.10x</b>. Spot Open Interest (SPOT_OBI) is also trending upwards at <b>0.886</b>.\n\nTime remaining: <b>14.1 minutes</b>.\n\nSignal consensus: <b>4/9</b> indicators aligned.\n\n\u26a0\ufe0f Not financial advice. For educational purposes only.",
      "outcome": "EXIT",
      "won": true,
      "pnl": 34.0,
      "resolved_at": "2026-05-31T08:06:02.059245+00:00",
      "exit_reason": "TAKE_PROFIT (89% of max)",
      "exit_price": 96
    }
  ]
};
