// Auto-generated by KalshiSnipe resolve_calls.py
const DASHBOARD_DATA = {
  "generated_at": "2026-06-04T04:15:10.008313+00:00",
  "total_calls": 1,
  "wins": 1,
  "losses": 0,
  "pending": 0,
  "win_rate": 1.0,
  "total_pnl": 1.5,
  "paper_stake_per_call": 25.0,
  "asset_stats": {
    "BTC": {
      "wins": 1,
      "losses": 0,
      "pnl": 1.5,
      "calls": 1
    }
  },
  "recent_calls": [
    {
      "ticker": "KXBTC15M-26JUN040015-15",
      "title": "BTC price up in next 15 mins?",
      "asset": "BTC",
      "called_direction": "YES",
      "mid_price_cents": 80,
      "yes_bid_dollars": "0.7900",
      "yes_ask_dollars": "0.8000",
      "minutes_left": 9.8,
      "consensus": 6,
      "edge_score": 0.6729,
      "close_time": "2026-06-04T04:15:00Z",
      "kalshi_url": "https://kalshi.com/markets/KXBTC15M",
      "posted_at": "2026-06-04T04:05:31.460370+00:00",
      "stake": 25.0,
      "paper_only": true,
      "post_text": "\ud83d\udfe2 **BTC** up in next 15 mins?\n\nMarket question: Will BTC price increase within the next 15 minutes?\n\nSeveral indicators suggest a potential short-term upward trend:\n- CVD (Coin Volume Delta) is +0.6269, indicating net buying pressure.\n- OBI (Order Book Imbalance) is at 0.8659, showing significant buying activity.\n- EMA (Exponential Moving Average) is up at 24.681379, supporting the upward trend.\n\nTime remaining: <b>9.8 minutes</b>\n\nSignal consensus: 6/9 indicators aligned\n\n<b>\ud83d\udd17 <a href=\"https://kalshi.com/markets/kxbtc15m/KXBTC15M-26JUN040015-15\">View on Kalshi</a></b>\n\n\u26a0\ufe0f Not financial advice. For educational purposes only.",
      "outcome": "EXIT",
      "won": true,
      "pnl": 1.5,
      "resolved_at": "2026-06-04T04:05:32.494889+00:00",
      "exit_reason": "TAKE_PROFIT_YES (price=86\u00a2 \u2265 80\u00a2)",
      "exit_price": 86,
      "exit_price_cents": 86,
      "reentry_eligible": false
    }
  ],
  "all_calls": [
    {
      "ticker": "KXBTC15M-26JUN040015-15",
      "title": "BTC price up in next 15 mins?",
      "asset": "BTC",
      "called_direction": "YES",
      "mid_price_cents": 80,
      "yes_bid_dollars": "0.7900",
      "yes_ask_dollars": "0.8000",
      "minutes_left": 9.8,
      "consensus": 6,
      "edge_score": 0.6729,
      "close_time": "2026-06-04T04:15:00Z",
      "kalshi_url": "https://kalshi.com/markets/KXBTC15M",
      "posted_at": "2026-06-04T04:05:31.460370+00:00",
      "stake": 25.0,
      "paper_only": true,
      "post_text": "\ud83d\udfe2 **BTC** up in next 15 mins?\n\nMarket question: Will BTC price increase within the next 15 minutes?\n\nSeveral indicators suggest a potential short-term upward trend:\n- CVD (Coin Volume Delta) is +0.6269, indicating net buying pressure.\n- OBI (Order Book Imbalance) is at 0.8659, showing significant buying activity.\n- EMA (Exponential Moving Average) is up at 24.681379, supporting the upward trend.\n\nTime remaining: <b>9.8 minutes</b>\n\nSignal consensus: 6/9 indicators aligned\n\n<b>\ud83d\udd17 <a href=\"https://kalshi.com/markets/kxbtc15m/KXBTC15M-26JUN040015-15\">View on Kalshi</a></b>\n\n\u26a0\ufe0f Not financial advice. For educational purposes only.",
      "outcome": "EXIT",
      "won": true,
      "pnl": 1.5,
      "resolved_at": "2026-06-04T04:05:32.494889+00:00",
      "exit_reason": "TAKE_PROFIT_YES (price=86\u00a2 \u2265 80\u00a2)",
      "exit_price": 86,
      "exit_price_cents": 86,
      "reentry_eligible": false
    }
  ]
};
